// Generated by tools/types.js from src/ — do not edit. Regenerate: npm run types
/** The fleet's announce-bus API, unchanged — existing callers keep working. */
export class AnnounceBus {
    /** @param {{ root?: ParentNode, regionId?: string }} [options] */
    constructor({ root, regionId }?: {
        root?: ParentNode;
        regionId?: string;
    });
    root: ParentNode;
    regionId: string;
    region: any;
    /** @param {string} text */
    announce(text: string): void;
    /** @param {string} label @param {number} position @param {number} total */
    announceMove(label: string, position: number, total: number): void;
    /** @param {string} label @param {boolean} selected */
    announceSelection(label: string, selected: boolean): void;
    /** @param {string} text */
    announceState(text: string): void;
}
export function announce(text: string): void;
