// Generated by tools/types.js from src/ — do not edit. Regenerate: npm run types
/** Base64url (RFC 4648 §5) without padding. */
export function base64UrlEncode(bytes: any): string;
/** 32 CSPRNG bytes → 43-char base64url. Also used for OAuth `state`. */
export function generateCodeVerifier(): string;
/** PKCE S256 challenge for a verifier. */
export function generateCodeChallenge(verifier: any): Promise<string>;
/**
 * Authorization-request URL: code flow + PKCE S256 + state. `extra` carries the
 * provider-specific params (Google: access_type/prompt; Cognito: identity_provider).
 * `state` is REQUIRED — a login without CSRF correlation is not expressible here.
 */
export function buildAuthorizeUrl({ authorizationEndpoint, clientId, redirectUri, scopes, challenge, state, extra }: {
    authorizationEndpoint: any;
    clientId: any;
    redirectUri: any;
    scopes: any;
    challenge: any;
    state: any;
    extra?: {} | undefined;
}): string;
/**
 * Backfill profile claims a lean token omits. Google's refresh-grant id_token carries
 * only sub/email/exp — re-parsing it blanks name + picture. Precedence: the parsed
 * token, then the in-memory user, then the persisted last-known-good profile. A
 * cache is only consulted when it belongs to the SAME `sub`.
 */
export function hydrateProfile(user: any, prev: any, stored: any): any;
/**
 * Pin a Google avatar to a small fixed size. Google varies the size suffix between
 * tokens, which busted URL-keyed caches; a stable URL is a stable cache key and a
 * small payload. Non-Google URLs pass through untouched.
 */
export function normalizeAvatarUrl(url: any): any;
/**
 * The refresh-rejection contract. A session is cleared ONLY when the refresh endpoint
 * explicitly rejects the refresh token: HTTP 401, or an OAuth error code of
 * `invalid_grant` (RFC 6749 §5.2 — what Cognito/Google return on a revoked token).
 * Transient failures (5xx, network, timeout, abort) keep the session; the next tick
 * retries. Message substrings are deliberately NOT consulted.
 */
export function isRefreshRejected(err: any): boolean;
/**
 * Delay until the proactive refresh should fire: `lead` ms before expiry, clamped to
 * [SOON, setTimeout max]. null when there is no usable expiry (nothing to schedule).
 */
export function refreshDelayMs(expiresAt: any, now?: number, lead?: number): number | null;
