// Generated by tools/types.js from src/ — do not edit. Regenerate: npm run types
export namespace auth {
    /**
     * Initialize auth state from storage or handle the OAuth callback.
     * Call this BEFORE router.init().
     * @param {{ keepAlive?: boolean, tokenStore?: 'local'|'session'|'memory'|Pick<Storage, 'getItem'|'setItem'|'removeItem'> }} [options]
     *   keepAlive (default true) arms the proactive refresh timer + visibility hook;
     *   an app that prefers to refresh only on demand passes { keepAlive: false }.
     *   tokenStore (default 'local') is where the token bundle and profile persist:
     *   'session' ends with the tab, 'memory' with the page, or pass an adapter.
     *   No store protects a token from script running in the page — SECURITY.md.
     */
    function init({ keepAlive, tokenStore }?: {
        keepAlive?: boolean;
        tokenStore?: "local" | "session" | "memory" | Pick<Storage, "getItem" | "setItem" | "removeItem">;
    }): Promise<void>;
    /** Check if user is authenticated (token present and not past expiry). */
    function isAuthenticated(): boolean;
    /** Alias for isAuthenticated — preferred for readability in UI code */
    function isLoggedIn(): boolean;
    /** Check if user has admin role. */
    function isAdmin(): boolean;
    /**
     * Ensure the token is valid, refreshing if inside the refresh window.
     * Concurrent callers (every gateway request calls this) share ONE refresh.
     * Resolves true when the token is usable, false when it is not.
     * @returns {Promise<boolean>}
     */
    function checkAndRefresh(): Promise<boolean>;
    /** Get the current Access Token, ensuring it is fresh. @returns {Promise<string|null>} */
    function getAccessToken(): Promise<string | null>;
    /** Get the current ID Token (JWT), ensuring it is fresh. @returns {Promise<string|null>} */
    function getIdToken(): Promise<string | null>;
    /** Get current user info. @returns {Object|null} */
    function getUser(): Object | null;
    /**
     * Initiate OAuth login with the specified provider.
     * @param {string} provider - 'Google', 'Facebook' (Cognito identity providers) or 'DirectGoogle'
     */
    function loginWith(provider?: string): Promise<void>;
    /** Log out and clear session. */
    function logout(): Promise<void>;
}
