// Generated by tools/types.js from src/ — do not edit. Regenerate: npm run types
export function saveRedirect(storage: any, path: any, now?: number): void;
/**
 * The app-internal form of a location pathname: deploy base stripped, leading
 * slash, no trailing slash, /index(.html) → /. Mirrors router.navigate's cleanPath.
 */
export function landingPath(pathname: any, base?: string): any;
/**
 * Always clears the stored value; returns the path to resume, or null.
 * `landings` adds app-specific sign-in landings (the router passes its loginPath).
 */
export function takeRedirect(storage: any, pathname: any, now?: number, ttlMs?: number, base?: string, landings?: any[]): string | null;
/**
 * Post-sign-in destination handoff. The router saves where a signed-out visitor
 * was going, and resumes it after the OAuth round trip lands back on the app.
 *
 * A saved destination is only honored when the app has just landed from sign-in
 * (OAuth returns to the root; the login feature then routes to /home) and only
 * while it is fresh. Without both checks, an abandoned sign-in left a destination
 * in storage that hijacked the user's NEXT visit, including a deep link opened
 * days later. Reconciled from scobot (Arc intent 48).
 */
export const REDIRECT_KEY: "axiom_auth_redirect";
export const REDIRECT_TTL_MS: number;
