// Generated by tools/types.js from src/ — do not edit. Regenerate: npm run types
/**
 * Runtime configuration. Everything here is PUBLIC — see axiom-config.js.
 * @typedef {{
 *   ENV: string,
 *   DEBUG: boolean,
 *   GRAPHQL_ENDPOINT: string,
 *   GRAPHQL_API_KEY: string,
 *   REST_ENDPOINT: string,
 *   readonly API_BASE: string,
 *   NEXUS_URL: string,
 *   AUTH: { USER_POOL_DOMAIN?: string, CLIENT_ID?: string, GOOGLE_CLIENT_ID?: string, REDIRECT_URI?: string, LOCAL_REDIRECT_URI?: string, TURNSTILE_SITE_KEY?: string },
 *   BASE_PATH: string,
 *   VERSION: string,
 *   NAV_STYLE: string,
 *   CONTENT_HOST: string,
 *   FEEDBACK_URL: string,
 *   TURNSTILE_SITE_KEY: string,
 *   [key: string]: any
 * }} AxiomConfig
 */
/** @type {Readonly<AxiomConfig>} */
export const config: Readonly<AxiomConfig>;
/**
 * Runtime configuration. Everything here is PUBLIC — see axiom-config.js.
 */
export type AxiomConfig = {
    ENV: string;
    DEBUG: boolean;
    GRAPHQL_ENDPOINT: string;
    GRAPHQL_API_KEY: string;
    REST_ENDPOINT: string;
    readonly API_BASE: string;
    NEXUS_URL: string;
    AUTH: {
        USER_POOL_DOMAIN?: string;
        CLIENT_ID?: string;
        GOOGLE_CLIENT_ID?: string;
        REDIRECT_URI?: string;
        LOCAL_REDIRECT_URI?: string;
        TURNSTILE_SITE_KEY?: string;
    };
    BASE_PATH: string;
    VERSION: string;
    NAV_STYLE: string;
    CONTENT_HOST: string;
    FEEDBACK_URL: string;
    TURNSTILE_SITE_KEY: string;
    [key: string]: any;
};
