// Generated by tools/types.js from src/ — do not edit. Regenerate: npm run types
/** Depth-first walk of the composed DOM tree, producing tab order. */
export function getTabOrder(): any[];
export function getDeepActiveElement(): Element | null;
