// Generated by tools/types.js from src/ — do not edit. Regenerate: npm run types
/**
 * @typedef {'auto'|'json'|'text'|'blob'|'xml'|'response'} Expect
 * @typedef {{ expect?: Expect }} GatewayOptions
 * @typedef {{ status?: number, statusText?: string, contentType?: string, url?: string, method?: string, body?: string, errors?: Array<{ message: string }>, data?: any, expect?: string, cause?: unknown }} GatewayFacts
 */
/**
 * A request that did not produce what the caller needed. Carries the facts a
 * handler branches on, so nobody parses a message string: status, statusText,
 * contentType, url, method, body (first 2 KB of the response text) — and for
 * GraphQL, errors[] and data.
 */
export class GatewayError extends Error {
    /**
     * @param {string} message
     * @param {GatewayFacts} [facts]
     */
    constructor(message: string, { cause, ...facts }?: GatewayFacts);
    /** @type {number|undefined} */ status: number | undefined;
    /** @type {string|undefined} */ statusText: string | undefined;
    /** @type {string|undefined} */ contentType: string | undefined;
    /** @type {string|undefined} */ url: string | undefined;
    /** @type {string|undefined} */ method: string | undefined;
    /** @type {string|undefined} first 2 KB of the response text */ body: string | undefined;
    /** @type {Array<{ message: string }>|undefined} GraphQL errors[] */ errors: Array<{
        message: string;
    }> | undefined;
    /** @type {any} GraphQL partial data */ data: any;
    /** @type {string|undefined} the refused expect value */ expect: string | undefined;
}
export namespace gateway {
    /**
     * Generic request handler
     * @param {string} method
     * @param {string} endpoint
     * @param {Object} [body]
     * @param {Object} [customHeaders]
     * @param {GatewayOptions} [options]
     *   'auto' (default) reads by content type, exactly as before. Any other value
     *   is an assertion (see the file header); 'response' returns the raw Response.
     * @returns {Promise<any>}
     */
    export function request(method: string, endpoint: string, body?: Object, customHeaders?: Object, { expect }?: GatewayOptions): Promise<any>;
    /** @param {string} endpoint @param {Record<string, string>} [headers] @param {GatewayOptions} [options] @returns {Promise<any>} */
    export function get(endpoint: string, headers?: Record<string, string>, options?: GatewayOptions): Promise<any>;
    /** @param {string} endpoint @param {any} [body] @param {Record<string, string>} [headers] @param {GatewayOptions} [options] @returns {Promise<any>} */
    export function post(endpoint: string, body?: any, headers?: Record<string, string>, options?: GatewayOptions): Promise<any>;
    /** @param {string} endpoint @param {any} [body] @param {Record<string, string>} [headers] @param {GatewayOptions} [options] @returns {Promise<any>} */
    export function put(endpoint: string, body?: any, headers?: Record<string, string>, options?: GatewayOptions): Promise<any>;
    /** @param {string} endpoint @param {Record<string, string>} [headers] @param {GatewayOptions} [options] @returns {Promise<any>} */
    function _delete(endpoint: string, headers?: Record<string, string>, options?: GatewayOptions): Promise<any>;
    export { _delete as delete };
    /**
     * Execute a GraphQL operation. The response must be JSON; errors[] rejects
     * with a GatewayError carrying them (and any partial data).
     * @param {string} operation - The query/mutation string
     * @param {Object} [variables] - Operation variables
     * @param {Object} [customHeaders] - Custom headers
     */
    export function graphql(operation: string, variables?: Object, customHeaders?: Object): Promise<any>;
}
export type Expect = "auto" | "json" | "text" | "blob" | "xml" | "response";
export type GatewayOptions = {
    expect?: Expect;
};
export type GatewayFacts = {
    status?: number;
    statusText?: string;
    contentType?: string;
    url?: string;
    method?: string;
    body?: string;
    errors?: Array<{
        message: string;
    }>;
    data?: any;
    expect?: string;
    cause?: unknown;
};
