// Generated by tools/types.js from src/ — do not edit. Regenerate: npm run types
export namespace log {
    function debug(msg: any, ...args: any[]): void;
    function info(msg: any, ...args: any[]): void;
    function warn(msg: any, ...args: any[]): void;
    function error(msg: any, ...args: any[]): void;
}
