// Generated by tools/types.js from src/ — do not edit. Regenerate: npm run types
/** Every event the core dispatches on window. */
export const EVENTS: readonly string[];
export function observe(handler: (name: string, detail: Record<string, any>) => void, names?: readonly string[]): () => void;
