// Generated by tools/types.js from src/ — do not edit. Regenerate: npm run types
export namespace router {
    let routes: Record<string, RouteConfig>;
    let depths: Record<string, number>;
    let order: string[];
    let defaultRoute: string;
    let base: string;
    /** @param {RouterOptions} [options] */
    function init(options?: RouterOptions): void;
    /** @param {string} slug @returns {number} */
    function getDepth(slug: string): number;
    /** @param {string} slug @returns {number} */
    function getOrder(slug: string): number;
    /**
     * Subscribe to navigation lifecycle events.
     * Callback receives the latest navigation object:
     * { phase: 'start' | 'commit', navigationId, path, cleanPath, slug, params?, direction, timestamp }
     * Returns an unsubscribe function.
     * @param {(nav: Navigation|null) => void} callback
     * @returns {() => void}
     */
    function onNavigation(callback: (nav: Navigation | null) => void): () => void;
    /**
     * Subscribe to route/params matches at commit time.
     * This is a convenience wrapper over navigation events for features
     * that care about the resolved route + params rather than raw paths.
     * @param {(match: { route: string, params: Record<string, string>, navigation: Navigation }) => void} callback
     * @returns {() => void}
     */
    function onMatch(callback: (match: {
        route: string;
        params: Record<string, string>;
        navigation: Navigation;
    }) => void): () => void;
    /**
     * @param {string} path
     * @param {boolean} [push] - true pushes a history entry; false replaces (back/forward, boot)
     * @param {string|null} [customDirection] - 'forward' | 'backward' | 'fade'; derived when omitted
     * @returns {Promise<void>}
     */
    function navigate(path: string, push?: boolean, customDirection?: string | null): Promise<void>;
    /** @param {MouseEvent} e */
    function handleIntercept(e: MouseEvent): void;
    /** @param {string} pattern @param {string} path @returns {Record<string, string>|null} */
    function matchRoute(pattern: string, path: string): Record<string, string> | null;
}
/**
 * One navigation, as published to state.navigation and onNavigation().
 */
export type RouteConfig = {
    path: string;
    guard?: () => boolean | Promise<boolean>;
    api?: string | ((params: Record<string, string>, signal: AbortSignal) => Promise<any>);
    dataKey?: string;
};
/**
 * A route. `path` is the feature module; `api` loads its data in parallel with it.
 */
export type Navigation = {
    phase: "start" | "commit";
    navigationId: number;
    path: string;
    cleanPath: string;
    slug: string;
    params?: Record<string, string>;
    direction: string;
    timestamp: number;
};
/**
 * A route. `path` is the feature module; `api` loads its data in parallel with it.
 */
export type RouterOptions = {
    routes?: Record<string, RouteConfig>;
    depths?: Record<string, number>;
    order?: string[];
    defaultRoute?: string;
    basePath?: string;
};
