// Generated by tools/types.js from src/ — do not edit. Regenerate: npm run types
export namespace state {
    let data: StateData;
    /** @param {string} key @returns {any} */
    function get(key: string): any;
    /**
     * Declare a key: its initial value and, optionally, where it persists. The one
     * place a key's storage is decided — core declares the framework's keys, and
     * an application declares its own from its own module.
     *
     *   state.define('volume', {
     *     initial: 80,
     *     storage: localStorage,              // or sessionStorage; omit = memory only
     *     storageKey: 'myapp-volume',         // default: the key itself
     *     parse: (raw) => parseInt(raw, 10),  // stored string -> value (default: as-is)
     *     serialize: String                   // value -> stored string (default)
     *   });
     *
     * A stored value wins over `initial`, and declaring a default never writes it.
     * Setting null/undefined removes the stored entry. Idempotent: defining a key
     * again returns its live value and changes nothing.
     * @template T
     * @param {string} key
     * @param {{ initial?: T, storage?: Pick<Storage, 'getItem'|'setItem'|'removeItem'>, storageKey?: string, parse?: (raw: string) => T, serialize?: (value: T) => string }} [options]
     * @returns {T} the key's current value
     */
    function define<T>(key: string, { initial, storage, storageKey, parse, serialize }?: {
        initial?: T;
        storage?: Pick<Storage, "getItem" | "setItem" | "removeItem">;
        storageKey?: string;
        parse?: (raw: string) => T;
        serialize?: (value: T) => string;
    }): T;
    /** @param {string} key @param {any} value */
    function set(key: string, value: any): void;
    /**
     * Functional update — the supported way to change NESTED data.
     * state.data is shallowly reactive: `state.data.user.name = 'x'` mutates the
     * held object in place, the Proxy never sees a set, and nothing re-renders.
     * Return the next value instead of mutating the current one:
     *     state.update('user', u => ({ ...u, name: 'x' }))
     * @template T
     * @param {string} key
     * @param {(current: T) => T} fn
     * @returns {T} the value that was set
     */
    function update<T>(key: string, fn: (current: T) => T): T;
    /** @template T, R @param {string} key @param {(value: T) => R} selectorFn @returns {R} */
    function select<T, R>(key: string, selectorFn: (value: T) => R): R;
    /**
     * Universal Query: Handles async sets with status tracking.
     * Automated "Loading", "Error", "Stale" states.
     * @template T
     * @param {string} key - The state key to populate
     * @param {() => Promise<T>} fetcher - Async function returning the data
     * @param {number} [ttl] - Time to live in ms (default 30s)
     * @returns {Promise<T>}
     */
    function query<T>(key: string, fetcher: () => Promise<T>, ttl?: number): Promise<T>;
    /**
     * Optimistic Mutation
     * Updates local state immediately, then runs the remote task. Safe to call
     * again on the same key while an earlier call is still in flight — see the
     * ledger at the top of this file. Resolves (never rejects) once THIS write has
     * settled; a failure is reported through notify() and the log.
     *
     * Contract: a failure removes exactly its own change. It never restores a
     * value some other, successful write has since replaced.
     * @param {string} key
     * @param {any} payload - an object merges into the current data; anything else replaces it
     * @param {() => Promise<unknown>} remoteTask
     * @returns {Promise<void>}
     */
    function mutate(key: string, payload: any, remoteTask: () => Promise<unknown>): Promise<void>;
    /**
     * @param {(change: { key: string, value: any }) => void} callback
     * @returns {() => void} unsubscribe
     */
    function subscribe(callback: (change: {
        key: string;
        value: any;
    }) => void): () => void;
    /**
     * Toast Notification Helper
     * Pushes a notification to state and auto-removes it.
     * @param {string} message - rendered as text, never markup
     * @param {'info'|'success'|'warning'|'error'} [type]
     * @param {number} [duration] - ms; 0 keeps it until dismissed
     */
    function notify(message: string, type?: "info" | "success" | "warning" | "error", duration?: number): void;
    /** @param {string} id */
    function dismissToast(id: string): void;
}
/**
 * The framework's keys. An application adds its own with state.define(), which
 * is why the index signature is open.
 */
export type Notification = {
    id: string;
    message: string;
    type: "info" | "success" | "warning" | "error";
    duration: number;
};
export type StateData = {
    route: string | null;
    query: Record<string, string>;
    params: Record<string, string>;
    navigation: import("./router.js").Navigation | null;
    navStyle: string;
    transition: {
        type: string;
        direction: string;
    };
    transitioning?: boolean;
    notifications: Notification[];
    theme?: string;
    user?: Object | null;
    [key: string]: any;
};
