// Generated by tools/types.js from src/ — do not edit. Regenerate: npm run types
export class BaseComponent extends HTMLElement {
    /** @type {Promise<void>} Resolves after the first render; the router awaits it. */
    rendered: Promise<void>;
    /**
     * AOM: ID Bridge Pattern
     * Generates a unique ID for the internal element and sets
     * aria-labelledby on the host if needed.
     * @param {Element|null} internalRef
     * @param {string} [suffix]
     * @returns {string}
     */
    bridgeID(internalRef: Element | null, suffix?: string): string;
    /**
     * Escape text for interpolation into innerHTML templates.
     * @param {unknown} str
     * @returns {string}
     */
    _esc(str: unknown): string;
    /**
     * Surgical Ref: Returns a cached node or finds it once.
     * @param {string} name
     * @param {string} selector
     * @returns {Element|null}
     */
    ref(name: string, selector: string): Element | null;
    /**
     * Dynamic Style Adoption: Allows features to add their own encapsulated styles
     * without affecting the global theme.
     * Sheets are memoized by CSS text: every control class passes the same
     * module-level constant, so N instances share ONE constructed sheet
     * instead of paying N parses (the same pattern as themeSheet above).
     * @param {string} cssString
     */
    addStyles(cssString: string): void;
    /**
     * Fetches external CSS and adopts it.
     * Workaround for lack of import ... with { type: 'css' } support.
     */
    /** @param {string} url @returns {Promise<void>} */
    addExternalStyles(url: string): Promise<void>;
    connectedCallback(): Promise<void>;
    /**
     * Universal Subscription Helper
     * Automatically handles cleanup when the component disconnects.
     * @param {string} targetKey - The state key to watch
     * @param {(value: any) => void} callback - Function to run on update
     */
    subscribe(targetKey: string, callback: (value: any) => void): void;
    disconnectedCallback(): void;
    render(): void;
}
