#!/usr/bin/env node
/**
 * tools/types.js — the public API as TypeScript declarations, generated from src/.
 *
 *   node tools/types.js           write types/ from the JSDoc in src/core + BaseComponent
 *   node tools/types.js --check   exit 1 if types/ differs from what src/ generates
 *
 * Declarations are derived, never hand-written, so they cannot silently drift from
 * the code — and --check (run by `npm test`) fails the build the moment they would.
 *
 * tsc's stripInternal does not reach members of the object-literal singletons
 * emitted from JavaScript (state, router, auth, gateway become namespaces), so
 * this tool removes underscore-prefixed members itself, on the AST: `_name` is
 * this codebase's convention for internal. Kept on purpose: `_esc` (the escape
 * helper component authors are told to use) and `_delete` (tsc's alias for the
 * reserved word `delete`, re-exported under that name).
 *
 * Exit codes: 0 ok · 1 --check found drift · 2 tsc reported errors.
 */
import fs from 'node:fs';
import path from 'node:path';
import ts from 'typescript';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const CONFIG = path.join(ROOT, 'tsconfig.types.json');
const OUT = path.join(ROOT, 'types');
const KEEP = new Set(['_esc', '_delete']);
const HEADER = '// Generated by tools/types.js from src/ — do not edit. Regenerate: npm run types\n';

const isInternal = (name) => typeof name === 'string' && name.startsWith('_') && !KEEP.has(name);
const identifierText = (n) => (n && ts.isIdentifier(n) ? n.text : undefined);
const statementNames = (s) => (ts.isVariableStatement(s)
  ? s.declarationList.declarations.map((d) => identifierText(d.name))
  : [identifierText(s.name)]);

/** Remove internal (underscore) members from namespaces and classes in a .d.ts. */
export const stripInternal = (text, fileName = 'x.d.ts') => {
  const source = ts.createSourceFile(fileName, text, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
  const transformer = (context) => {
    const visit = (node) => {
      if (ts.isModuleBlock(node)) {
        const kept = node.statements.filter((s) => {
          const names = statementNames(s).filter(Boolean);
          return !(names.length && names.every(isInternal));
        });
        return ts.factory.updateModuleBlock(node, ts.visitNodes(ts.factory.createNodeArray(kept), visit));
      }
      if (ts.isClassDeclaration(node)) {
        const kept = node.members.filter((m) => !isInternal(identifierText(m.name)));
        return ts.factory.updateClassDeclaration(node, node.modifiers, node.name, node.typeParameters, node.heritageClauses, kept);
      }
      return ts.visitEachChild(node, visit, context);
    };
    return (root) => ts.visitNode(root, visit);
  };
  const [out] = ts.transform(source, [transformer]).transformed;
  return HEADER + ts.createPrinter({ newLine: ts.NewLineKind.LineFeed }).printFile(out);
};

const listDts = (dir, base = dir) => (fs.existsSync(dir)
  ? fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => (e.isDirectory()
    ? listDts(path.join(dir, e.name), base)
    : e.name.endsWith('.d.ts') ? [path.relative(base, path.join(dir, e.name))] : []))
  : []);

export const generate = () => {
  const parsed = ts.getParsedCommandLineOfConfigFile(CONFIG, {}, {
    ...ts.sys,
    onUnRecoverableConfigFileDiagnostic: (d) => { throw new Error(ts.flattenDiagnosticMessageText(d.messageText, '\n')); },
  });
  const program = ts.createProgram({ rootNames: parsed.fileNames, options: parsed.options });
  const files = new Map();
  const emitted = program.emit(undefined, (fileName, text) => {
    if (fileName.endsWith('.d.ts')) files.set(path.relative(OUT, fileName), stripInternal(text, fileName));
  }, undefined, true);
  return { files, diagnostics: [...ts.getPreEmitDiagnostics(program), ...emitted.diagnostics] };
};

const main = (argv) => {
  const { files, diagnostics } = generate();
  if (diagnostics.length) {
    console.error(ts.formatDiagnostics(diagnostics, {
      getCanonicalFileName: (f) => f, getCurrentDirectory: () => ROOT, getNewLine: () => '\n',
    }));
    return 2;
  }
  if (argv.includes('--check')) {
    const onDisk = new Map(listDts(OUT).map((rel) => [rel, fs.readFileSync(path.join(OUT, rel), 'utf8')]));
    const drift = [...new Set([...files.keys(), ...onDisk.keys()])].filter((rel) => files.get(rel) !== onDisk.get(rel));
    if (!drift.length) { console.log(`types: ${files.size} declaration files current`); return 0; }
    console.error(`types: ${drift.length} file(s) out of date — run npm run types:\n  ${drift.join('\n  ')}`);
    return 1;
  }
  fs.rmSync(OUT, { recursive: true, force: true });
  for (const [rel, text] of files) {
    fs.mkdirSync(path.dirname(path.join(OUT, rel)), { recursive: true });
    fs.writeFileSync(path.join(OUT, rel), text);
  }
  console.log(`types: wrote ${files.size} declaration files to types/`);
  return 0;
};

if (process.argv[1] === fileURLToPath(import.meta.url)) process.exitCode = main(process.argv.slice(2));
